bind_address = "0.0.0.0:8080"
origin = "http://idmouse.idmouse.svc"

# Roles are required unless the service is started with --disable-auth.
[[role]]
name = "idelephant-source"
audience = "idmouse"
issuer = "https://kubernetes.default.svc"
validation-key = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTljJr11MDnf6FGOXi07
EUqrmLKrT/9tPEJd98zYCP+3oUaqvDDnq72wSWmwmztjxun4O4kotsuExhitnVQ5
2p2W8fd/bgaw88G1Ud2FVe0k0BKTVZuh7jFlFaLCmzC4L+H3F3wuxVWW4KtoAW5W
lRnmMR5fvsrANs2zhIF2sEme0Y+zS/kxaWLLniq9E+OvbRUtLEDnoiDOvei/diAY
DXl7MVlwWE2RhaVnEHgMiIJbzpDGoSxYcpM0WbSX9OJp2vGt2y8wVJ4JKmkvEbLn
QNomSRZMTkPmzXK+GjSJAw90ImP+lHXlzwyZUJq1h0hbE5BvxnmQi/NbwH9CSPWm
HwIDAQAB
-----END PUBLIC KEY-----
"""

[role.claims]
sub = "system:serviceaccount:idelephant:idelephant"

[[role]]
name = "default-source"
audience = "idmouse"
issuer = "https://kubernetes.default.svc"

[role.claims]
sub = "system:serviceaccount:default:default"

[[mapping]]
name = "idelephant"
role = "idelephant-source"
additional_claims = { ns = "default", db = "idelephant", sub = "idelephant", ac = "idelephant", rl = ["Editor"] }

[[mapping]]
name = "some_other_mapping"
role = "default-source"
additional_claims = { ns = "ns_name", db = "foo" }

[[mapping]]
name = "root"
role = "default-source"
additional_claims = { ac = "root", rl = ["Owner"] }
