bind_address = "0.0.0.0:8080"
origin = "http://idmouse.idmouse.svc"

# This section is required unless the service is started with --disable-auth.
[authentication]
audience = "idmouse"
issuer = "https://kubernetes.default.svc"
validation_key = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTljJr11MDnf6FGOXi07
EUqrmLKrT/9tPEJd98zYCP+3oUaqvDDnq72wSWmwmztjxun4O4kotsuExhitnVQ5
2p2W8fd/bgaw88G1Ud2FVe0k0BKTVZuh7jFlFaLCmzC4L+H3F3wuxVWW4KtoAW5W
lRnmMR5fvsrANs2zhIF2sEme0Y+zS/kxaWLLniq9E+OvbRUtLEDnoiDOvei/diAY
DXl7MVlwWE2RhaVnEHgMiIJbzpDGoSxYcpM0WbSX9OJp2vGt2y8wVJ4JKmkvEbLn
QNomSRZMTkPmzXK+GjSJAw90ImP+lHXlzwyZUJq1h0hbE5BvxnmQi/NbwH9CSPWm
HwIDAQAB
-----END PUBLIC KEY-----
"""

[[mapping]]
name = "idelephant"
allowed_subjects = ["system:serviceaccount:idelephant:idelephant"]
additional_claims = { ns = "default", db = "idelephant", sub = "idelephant", ac = "idelephant", rl = ["Editor"] }

[[mapping]]
name = "some_other_mapping"
allowed_subjects = ["system:serviceaccount:default:default"]
additional_claims = { ns = "ns_name", db = "foo" }

[[mapping]]
name = "root"
additional_claims = { ac = "root", rl = ["Owner"] }
